<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Add To Cart Test"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="47.150">
    <properties></properties>

            <testcase
                name="tc0010_verify_price_display_test"
                time="4.800"
                classname="testcases.TestAddToCart">

            <failure type="java.lang.AssertionError" message="expected [$34.95 USD] but found []">
                <![CDATA[java.lang.AssertionError: expected [$34.95 USD] but found []
                org.testng.Assert.fail(Assert.java:96)org.testng.Assert.failNotEquals(Assert.java:776)org.testng.Assert.assertEqualsImpl(Assert.java:137)org.testng.Assert.assertEquals(Assert.java:118)org.testng.Assert.assertEquals(Assert.java:453)org.testng.Assert.assertEquals(Assert.java:463)testcases.TestAddToCart.tc0010_verify_price_display_test(TestAddToCart.java:35)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)org.testng.internal.Invoker.invokeMethod(Invoker.java:583)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:648)org.testng.TestRunner.run(TestRunner.java:505)org.testng.SuiteRunner.runTest(SuiteRunner.java:455)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)org.testng.SuiteRunner.run(SuiteRunner.java:364)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)org.testng.TestNG.runSuitesLocally(TestNG.java:1137)org.testng.TestNG.runSuites(TestNG.java:1049)org.testng.TestNG.run(TestNG.java:1017)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


            <testcase
                name="tc0012_refresh_page_test"
                time="9.721"
                classname="testcases.TestAddToCart">
            </testcase>
            <testcase
                name="tc0015_remove_item_from_cart_test"
                time="13.585"
                classname="testcases.TestAddToCart">
            </testcase>
            <testcase
                name="tc0014_verify_correct_quantity_displayed_test"
                time="6.262"
                classname="testcases.TestAddToCart">
            </testcase>
            <testcase
                name="tc0011_verify_product_added_to_cart_test"
                time="6.122"
                classname="testcases.TestAddToCart">
            </testcase>
            <testcase
                name="tc0013_increase_item_quantity_test"
                time="6.660"
                classname="testcases.TestAddToCart">
            </testcase>
</testsuite>
